version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-instagram
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin-instagram
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin/
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge